# default config.yml
#maximum vertical current length
MAX_V: 7
#0 - normal fence; 1 - netherbrick fence
FENCE_TYPE: 0
LAMP_ON: 89
LAMP_OFF: 20
#try to change this if you have problems
LAMP_DATA: 12
